"""
PR Reviewer — Scenario 2.

Fetches PR files from Azure DevOps, runs the compliance checker,
posts structured feedback comments, and sets the PR vote/status.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass

from shared.ado_client import ADOClient, PRComment
from shared.utils import truncate

from .compliance_checker import ComplianceReport, ComplianceFinding

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🟢",
    "INFO": "ℹ️",
}

_VERDICT_EMOJI = {
    "PASS": "✅",
    "FAIL": "❌",
}


def _render_comment(report: ComplianceReport, pr_id: int) -> str:
    """Render a Markdown PR comment from a compliance report."""
    verdict_emoji = _VERDICT_EMOJI.get(report.verdict, "❓")
    lines = [
        f"## {verdict_emoji} AI Compliance Review — **{report.verdict}**",
        "",
        f"_{report.summary}_",
        "",
    ]

    if report.findings:
        lines += ["### Findings", ""]
        for finding in report.findings:
            emoji = _SEVERITY_EMOJI.get(finding.severity, "⚪")
            lines += [
                f"#### {emoji} `{finding.severity}` — {finding.rule}",
                f"**File:** `{finding.file}`",
            ]
            if finding.line_hint:
                lines.append(f"**Location:** {finding.line_hint}")
            lines += [
                "",
                finding.description,
                "",
                f"💡 **Recommendation:** {finding.recommendation}",
                "",
                "---",
                "",
            ]

    if report.compliant_items:
        lines += ["### ✅ Compliant Items", ""]
        for item in report.compliant_items:
            lines.append(f"- {item}")
        lines.append("")

    lines += [
        "---",
        "_Generated by the AI PR Compliance agent. "
        "Review findings carefully before merging._",
    ]

    return "\n".join(lines)


@dataclass
class ReviewResult:
    """Outcome of a PR review cycle."""

    pr_id: int
    verdict: str
    comment_thread_id: int | None
    status_state: str


class PRReviewer:
    """
    Fetches PR diff, drives the compliance check, and posts results back to ADO.
    """

    def __init__(self, ado_client: ADOClient | None = None) -> None:
        self._ado = ado_client or ADOClient()
        self.repo_id = os.environ.get("ADO_REPOSITORY_ID", "")

    def review(
        self,
        pr_id: int,
        report: ComplianceReport,
        repo_id: str | None = None,
    ) -> ReviewResult:
        """
        Post compliance findings as a PR comment and update the PR status.

        Args:
            pr_id: Pull request ID.
            report: Compliance report from :class:`ComplianceChecker`.
            repo_id: Repository GUID (falls back to ADO_REPOSITORY_ID env var).

        Returns:
            :class:`ReviewResult` summarising what was posted.
        """
        repo_id = repo_id or self.repo_id
        if not repo_id:
            raise EnvironmentError(
                "ADO_REPOSITORY_ID is not set. Cannot post PR comment."
            )

        # Post comment thread
        comment_text = _render_comment(report, pr_id)
        comment = PRComment(
            content=comment_text,
            status="active" if not report.is_passing else "resolved",
        )
        thread = self._ado.post_pr_comment(
            repo_id=repo_id,
            pr_id=pr_id,
            comment=comment,
        )
        thread_id: int | None = thread.get("id")

        # Update PR status (used by branch policy to block/approve)
        status_state = "succeeded" if report.is_passing else "failed"
        self._ado.update_pr_status(
            repo_id=repo_id,
            pr_id=pr_id,
            state=status_state,
            description=(
                f"AI Compliance: {report.verdict} — {truncate(report.summary, 100)}"
            ),
            context_name="ai-pr-compliance",
            context_genre="ai-devsecops",
        )

        logger.info(
            "PR %d review complete: verdict=%s status=%s thread_id=%s",
            pr_id,
            report.verdict,
            status_state,
            thread_id,
        )

        return ReviewResult(
            pr_id=pr_id,
            verdict=report.verdict,
            comment_thread_id=thread_id,
            status_state=status_state,
        )
