"""
Wiki Publisher — Scenario 1.

Renders root cause findings as Markdown and upserts them to an
Azure DevOps Wiki page.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from shared.ado_client import ADOClient
from shared.utils import utcnow_iso

from .root_cause_clusterer import RootCauseFinding

logger = logging.getLogger(__name__)

_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🟢",
}


def _render_finding(finding: RootCauseFinding, index: int) -> str:
    emoji = _SEVERITY_EMOJI.get(finding.severity, "⚪")
    steps_md = "\n".join(f"{i+1}. {step}" for i, step in enumerate(finding.remediation_steps))
    pipelines_md = ", ".join(f"`{p}`" for p in finding.affected_pipelines) or "_unknown_"
    branches_md = ", ".join(f"`{b}`" for b in finding.affected_branches) or "_unknown_"
    occurrence_count = finding.pattern.count

    return f"""\
## {index}. {emoji} {finding.title}

| Field | Value |
|---|---|
| **Severity** | {finding.severity} |
| **Occurrences** | {occurrence_count} |
| **Affected Pipelines** | {pipelines_md} |
| **Affected Branches** | {branches_md} |

### Root Cause

{finding.root_cause}

### Remediation Steps

{steps_md}

---
"""


def render_wiki_page(
    findings: list[RootCauseFinding],
    generated_at: str | None = None,
) -> str:
    """
    Render a full Wiki page in Markdown from a list of findings.

    Args:
        findings: Ordered list of root cause findings (highest severity first).
        generated_at: ISO 8601 timestamp string (defaults to now).

    Returns:
        Markdown string ready for publishing.
    """
    generated_at = generated_at or utcnow_iso()

    if not findings:
        return f"""\
# 🤖 AI Build Intelligence — Failure Report

_Generated: {generated_at}_

No failure patterns were detected in the latest analysis cycle. ✅
"""

    header = f"""\
# 🤖 AI Build Intelligence — Failure Report

_Generated by the AI Build Intelligence agent on {generated_at}_
_Total patterns identified: **{len(findings)}**_

---
"""
    toc_lines = []
    for i, finding in enumerate(findings, 1):
        emoji = _SEVERITY_EMOJI.get(finding.severity, "⚪")
        anchor = finding.title.lower().replace(" ", "-").replace("/", "").replace(".", "")
        toc_lines.append(f"{i}. [{emoji} {finding.title}](#{i}-{anchor})")

    toc = "## Table of Contents\n\n" + "\n".join(toc_lines) + "\n\n---\n"

    body = "\n".join(_render_finding(f, i) for i, f in enumerate(findings, 1))

    return header + toc + "\n" + body


class WikiPublisher:
    """Publishes rendered Markdown reports to an Azure DevOps Wiki page."""

    def __init__(self, ado_client: ADOClient | None = None) -> None:
        self._client = ado_client or ADOClient()
        self.wiki_id = os.environ.get("ADO_WIKI_ID", "")
        self.wiki_path = os.environ.get(
            "ADO_WIKI_PATH", "/Build-Intelligence/Failure-Report"
        )

    def publish(self, findings: list[RootCauseFinding]) -> str:
        """
        Render findings and upsert to the configured Wiki page.

        Args:
            findings: Root cause findings to publish.

        Returns:
            The wiki page path that was updated.
        """
        if not self.wiki_id:
            raise EnvironmentError(
                "ADO_WIKI_ID is not set. Cannot publish to Wiki."
            )

        content = render_wiki_page(findings)
        etag = self._client.get_wiki_page_version(self.wiki_id, self.wiki_path)

        self._client.upsert_wiki_page(
            wiki_id=self.wiki_id,
            path=self.wiki_path,
            content=content,
            version=etag,
        )
        logger.info(
            "Published %d findings to Wiki page '%s' (wiki=%s)",
            len(findings),
            self.wiki_path,
            self.wiki_id,
        )
        return self.wiki_path
